// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gitstats} from '../models';

export function GetDashboardSnapshot():Promise<gitstats.DashboardSnapshot>;
